### ISSUE TITLE
ForceField效果的三个小问题

### ISSUE THREAD

**Issue by hustanhuang** [chenjd/UnitySpecialEffectWithDepth#2]
110行的_DistortTimeFactor是不是应该在tex2D里面去乘_Time.xy？
这样写去乘采样结果有点意义不明啊。。

第二就是GrabPass的时候给了个名字，那前后两个力场效果重叠的时候用的同一个GrabTex，效果上是有点问题的。
但是如果独立grab，一方面是性能问题，另一方面我试了一下好像也没有完全解决重叠的问题。

还有就是会有未扭曲的成分仍然会被混合进去，不过我不知道是不是特意为之。

**Comment by chenjd** [comment]
恩。
GrabPass给名字是一个性能上的考虑。
这个是护罩的shader，全都是扭曲的。
